"""Your migration message here

Revision ID: 1accb3934e07
Revises: 67a3e67a740d
Create Date: 2025-05-03 01:54:24.020543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1accb3934e07'
down_revision = '67a3e67a740d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_school_subject', sa.String(length=100), nullable=True))
        batch_op.drop_column('fav_school_sub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fav_school_sub', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('fav_school_subject')

    # ### end Alembic commands ###
